WIP: install fud
error in running tests via `installCheckPhase`:
```
ModuleNotFoundError: No module named 'calyx'
```

-> need to include `calyx-py` module?